services:
  postgres:
    image: postgres:17
    container_name: payment-platform-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: payment_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Kolkata
      PGTZ: Asia/Kolkata

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: