spring.application.name=payment-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/payment_platform
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true